eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 9007
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.archi-lab.io/auth/realms/archilab