eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 9007
spring:
  application:
    name: prox-user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.archi-lab.io/auth/realms/archilab
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    password: user-service
    url: jdbc:postgresql://user-service-db:5432/user-service-db
    username: user-service