{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-user-service.fullname" . }}
  labels:
    {{- include "prox-user-service.labels" . | nindent 4 }}
data:
  "database-host": prox-user-service-db
  "database-port": 5432
  "database-name": postgres
  "keycloak.server-url": https://login.aws.innovation-hub.de/auth
  "keycloak.realm": innovation-hub-bergisches-rheinland
  "keycloak.client-id": prox-user-service
  {{- end }}
