{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-user-service.fullname" . }}
  labels:
    {{- include "prox-user-service.labels" . | nindent 4 }}
data:
  databaseHost: prox-user-service-db
  databasePort: 5432
  databaseName: postgres
  keycloakServerUrl: https://login.aws.innovation-hub.de/auth
  keycloakRealm: innovation-hub-bergisches-rheinland
  keycloakClientId: prox-user-service
  {{- end }}
