{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prox-user-service.fullname" . }}
  labels:
    {{- include "prox-user-service.labels" . | nindent 4 }}
type: Opaque
data:
  "database-user": {{ include "prox-user-service.database-user" . }}
  "database-password": {{ include "prox-user-service.database-password" . }}
  "replication-user-password": {{ include "prox-user-service.replication-user-password" . }}
  "keycloak.client-secret": {{ include "prox-user-service.keycloak.client-secret" . }}
  "aws.credentials.access-key-id": {{ include "prox-user-service.aws.credentials.access-key-id" . }}
  "aws.credentials.secret-access-key": {{ include "prox-user-service.aws.credentials.secret-access-key" . }}
{{- end }}
