{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prox-user-service.fullname" . }}
  labels:
    {{- include "prox-user-service.labels" . | nindent 4 }}
type: Opaque
data:
  databaseUser: {{ include "prox-user-service.databaseUser" . }}
  databasePassword: {{ include "prox-user-service.databasePassword" . }}
  replicationUserPassword: {{ include "prox-user-service.replicationUserPassword" . }}
  keycloakClientSecret: {{ include "prox-user-service.keycloakClientSecret" . }}
{{- end }}
