{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prox-user-service.fullname" . }}
  labels:
    {{- include "prox-user-service.labels" . | nindent 4 }}
type: Opaque
data:
  "database-user": {{ include "prox-user-service.databaseUser" . }}
  "database-password": {{ include "prox-user-service.databasePassword" . }}
  "replication-user-password": {{ include "prox-user-service.replicationUserPassword" . }}
  "keycloak-client-secret": {{ include "prox-user-service.keycloakClientSecret" . }}
{{- end }}
