name: CI

on:
  # Run on every pull request
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  JAVA_VERSION: 17

# Will build the binaries, run tests and checks on them and if everything succeeds AND it is a push
# to the main branch will build and deploy a snapshot release of the binaries

jobs:
  # Basic Gradle wrapper validation. This step is run first, due to security
  # concerns. Running our whole pipeline with Gradle with a corrupt wrapper,
  # could expose our secrets, and we definitely want to prevent this.
  validation:
    name: Gradle wrapper validation

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  assemble:
    name: Build

    runs-on: ubuntu-latest
    needs: [ validation ]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      - name: Gradle Assemble
        run: |
          ./gradlew --stacktrace assemble

  test:

    runs-on: ubuntu-latest
    needs: [ validation ]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      - name: Gradle test
        run: |
          ./gradlew --stacktrace test

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build reports
          path: build/reports

  codestyle:

    runs-on: ubuntu-latest
    needs: [ validation ]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      - name: Gradle Codestyle Check
        run: |
          ./gradlew --stacktrace spotlessCheck

  sonarcloud:
    name: SonarCloud analysis

    runs-on: ubuntu-latest
    needs: [ validation, assemble, test ]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          # Sonar needs the whole Git history for issue assignment
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      - name: Cache SonarCloud results
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache/
          key: ubuntu-sonar

      - name: SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew jacocoTestReport sonarqube --stacktrace -i


  build-image:
    name: Build Docker Image

    runs-on: ubuntu-latest
    needs: [ validation, assemble, test ]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      - name: Jib Docker Build
        run: ./gradlew build -Dquarkus.container-image.build=true

#  release:
#    name: Release
#
#    needs: [ validation, test, build-image ]
#
#    # Only run if a tag is created
#    if: startsWith(github.ref, 'refs/tags/v')
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Set up JDK ${{ env.JAVA_VERSION }}
#        uses: actions/setup-java@v2
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Login to Quay
#        uses: docker/login-action@v1
#        with:
#          registry: quay.io
#          username: ${{ secrets.QUAY_IO_USERNAME }}
#          password: ${{ secrets.QUAY_IO_PASSWORD }}
#
#      - name: Get Project version
#        id: project
#        run: |
#          echo ::set-output name=version::$(cat version.txt)
#
#      - name: Download build
#        uses: actions/download-artifact@v2
#        with:
#          path: ./target
#          name: maven-target.zip
#
#      - name: Maven Deploy
#        run: |
#          mvn -nsu -B -e -Prelease -DskipTests -Djib.to.tags=latest,${{ steps.project.outputs.version }} deploy
#
#      - name: Publish Helm charts
#        uses: stefanprodan/helm-gh-pages@master
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          charts_dir: ./deploy/charts
#          app_version: ${{ steps.project.outputs.version }}
#          chart_version: ${{ steps.project.outputs.version }}
